sudo: false
language: node_js
node_js:
- stable
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- npm run build
- npm test
deploy:
  provider: npm
  email: iwata0303@gmail.com
  on:
    tags: true
  skip_cleanup: true
  api_key:
    secure: ELjuIa/Zrg269S4gXulJQeL7OJJCvw4Og9iZLz1uq0PsAYZGoP4IBtQSvS3Wn/QOPPNpr7O+YJFxKxGJmf+VHX/2t+jHlVBClRrsvGwXjatS0RmIviQVZpYjBtJt7Y5Dgz/Z/bp2kggjxbDGWzlC2uka4orgmUa2ljPo/j4+eM1x3ro7fdFjxCnio+9yCXo4NPH8atJ1sniuvfkalIS6Sc1J5vsAiad3lA6/QSj9+QlyKLZJBJIjT/jOyfAsk/j4k93zCvdMfXyJYMEauyH3zNmTpMB8fnO9m+TKYjHpuMyBUFXIdD9afWupxMeskq4u0AZZA2PdPdOK/za2/mEyvoiXRTvc1K40EwzgqINBsmDp1m1VJwoyH5pugBVit8tqOmSaHgDvc3cG7j50mp3WSQMXysHv7yI0VFWRYqZZnrcP4ArJaREqudUKLxRdtDMydkDCa2p1xXxGnoTALzlY+1RDuKSXS3kkg7SVqWei69UlSBaY/qoVXxY23682CjGxBFsFKI9XrXHANHbkGnJ8RX3oBwnJFWieF0JFC8serLj+PEITnkSJgc80rU1YEuxJ7+J0H6NHH1U84ATAA8zRJT1lPYnAO2FY7L8ciTjFvXKyCkurNZxYJFvvOychoqH0+veDITpnIyxwASn3qmRZ3+9Z1wZYLUWvT5pqLmSoaeg=
